### ISSUE TITLE
how to calculate the speedup？

### ISSUE THREAD

**Issue by cjnewstar111** [dmlc/mxnet#1001]
hello，I‘ m a new comer in deep learning and i want to ask a question about how to calculate the speedup. for example , while i use one gpu for trainning, i set the batch_size  256, and when i use two gpus , how to set the batch_size, is still 256 or 512?  after this , i should use which speed to calculate the speedup?  somebody saied just use the imaege processing speed,such as 300 samples/sec , but others told that i shold use the time which one epoch spent. This really confused me. thanks .

**Comment by mli** [comment]
1. i suggest to use 512 for two gpus for better system performance. but if your problem is tiny, you probably need to reduce this number for better convergence

2. if you use codes in `example/image-classification`, it will produce xxx samples/sec for every 50 or 100 batches. if you find that number dosn't change from time to time (often not), then you can use it
