### ISSUE TITLE
Passing in symbols for auxiliary states

### ISSUE THREAD

**Issue by lukemetz** [dmlc/mxnet#1012]
Is this currently possible like what is done for passing in arguments?
https://github.com/dmlc/mxnet/blob/514acea29882b4031d57aac4cb506ab39439782a/doc/python/symbol_in_pictures.md#auxiliary-states suggests it but I get errors along the lines of:

```
*** MXNetError: [21:07:18] src/symbol/symbol.cc:121: Symbol.ComposeKeyword argument name rolling_mean not found.
Candidate arguments:
	[0]data
	[1]gamma
	[2]beta
```
I am trying to make an generative adversarial network that shares copies of batchnorm ops. I have the arguments synced up by passing in `Symbol`'s but upon doing this I get duplicate name errors on aux states.

Sorry for all the questions and thanks!

**Comment by piiswrong** [comment]
If it's a symbol why not put it in input?

**Comment by lukemetz** [comment]
I am trying to pass in the symbol as an auxiliary state. For example:
``` python
r = mx.sym.Variable("rolling")
output = mx.sym.BatchNorm(data=data, rolling_var=r)
```
Is this dumb to do?

**Comment by tqchen** [comment]
Currently, auxiliary states can only be binded separately and cannot be shared, mainly because each op can mutate these states.

However, as auxiliary states in BatchNorm are not used during training(only updated via statistics accumulation), but only used for prediction. You can do the averaging after the training before running prediction, as in the multi device training.

**Comment by lukemetz** [comment]
Thank you. I will deal with them post training.
