### ISSUE TITLE
Issue installing mxnet R-package using gpu on Windows

### ISSUE THREAD

**Issue by chibberto** [dmlc/mxnet#1336]
Hi, I'm having problems trying to install mxnet in R when using the pre-built windows binary hosted here 
https://github.com/dmlc/mxnet/releases

and using the instructions on the Installation Guide page. All seems to work ok, in that the mxnet library for R gets created. However, when I run the Handwritten Digits Tutorial using LeNet, when using the gpu it doesn't seem to optimise correctly. I've downloaded the windows release and the zip from github today.

Training using cpu (similar to example) 
Start training with 1 devices
[1] Train-accuracy=0.55708830548926

Training using gpu (different to example)
Start training with 1 devices
[1] Train-accuracy=0.0983770883054893
[2] Train-accuracy=0.0983809523809524
[3] Train-accuracy=0.0983809523809524
[4] Train-accuracy=0.0983809523809524
[5] Train-accuracy=0.0983809523809524

I realise that from the information i've given it's going to be hard to diagnose, and I probably have made a mistake during installation. Any help would be appreciated.

Regards,
Chris

I have attached the log when I run R CMD INSTALL ...
[mxnet R CMD INSTALL Output.txt](https://github.com/dmlc/mxnet/files/101155/mxnet.R.CMD.INSTALL.Output.txt)

**Comment by thirdwing** [comment]
Can double check the gpu is actually used when running R scripts?

**Comment by chibberto** [comment]
Yes, I believe so. GPU Load goes from 0% to 84% when training is running. Thanks for your help.
Chris

**Comment by thirdwing** [comment]
Your log seems correct. Sorry that I don't have a Windows machine to reproduce your result.

**Comment by junshui** [comment]
I ran into the similar problem. The "Train-accuracy" remains the same from the second output on.

**Comment by junshui** [comment]
The older pre-built packages (until windows binary build 20151228) do not have this problem. It seems that the problem started with those packages built in 2016.

**Comment by thirdwing** [comment]
So this might be a problem about pre-built Windows lib.

@hjk41 Can you help us on this?

**Comment by narayaba** [comment]
Does any one have a solution to this? I am having the same issue on a 64 bit windows (8.1) platform in R. The mxnet library got created with no error but the classification accuracy does not replicate on GPU. The CPU runs ok with accuracy of 0.557088. Any suggestions. I am using the (prebuilt) windows binary build 20160120.

Thanks

**Comment by sanson87** [comment]
Same issue here, accuracy remains stuck from the second run. Would be interested if anyone has a suggestion. Thanks a lot.

**Comment by hjk41** [comment]
@thirdwing @sanson87 @narayaba @chibberto @junshui 
Sorry guys for taking so long to respond. It seems to be a common problem. I have started working on it. Currently I have failed to reproduce the problem on the machine where I compiled the code. I will move to another machine and see if it is a configuration problem. Could you guys also help by trying the following?
1. run "where libmxnet.dll" and see if you are using the right version of libmxnet.dll
2. run matrixMulCuBLAS from nvidia CUDA samples and see if it works
3. try building mxnet from source and do the test again

Since it is the same problem with #1228. Let's all move to issue #1228 for this problem. Thanks!
