### ISSUE TITLE
training the ImageNet model

### ISSUE THREAD

**Issue by zjubxl123** [dmlc/mxnet#152]
I have successfully run the mxnet on Mnist dataset using the python scripts in the example. However, when running the ImageNet example, error occured. First I run the data.py (this is normal without error) and then alexnet.py , error prompted announcing that Segmentation fault (core dumped). 

In the data.py, what is the data structure of  " path_imgrec= "data/ilsvrc12/train.rec" ", and how to generate the data ? What should be done before running alexnet.py on ImageNet Dataset ?

**Comment by antinucleon** [comment]
Thanks for trying new tools. We don't finish all things in MXNet yet. We will make a detailed doc about how to train ImageNet. ```data.py``` is not for generating data but declaration of data iterator. The segfault is because DataIter didn't find the image rec file in path, We will make a more clear error info.
-----

We hope to finish all docs and code in today or tomorrow.

**Comment by tqchen** [comment]
The dataset information can be found here http://mxnet.readthedocs.org/en/latest/python/io.html

**Comment by tqchen** [comment]
check out https://github.com/dmlc/mxnet/tree/master/example/imagenet has been updated
