### ISSUE TITLE
Problem for IO

### ISSUE THREAD

**Issue by channerduan01** [dmlc/mxnet#1523]
Dear friends, I have 2 problems for CSVIter:

1, Is it possible(and how) to add some preprocess for every batch before the data feed into model. I am going to introduce random factor into preprocess, so I want to it happens before the feeding every time otherwise I have to prepare lots of data.

2, I am confused about the 'shuffle' of CSVIter. I set 'shuffle=True' on my test data and got the same results with 'shuffle=False', I expected the order of the results should be shuffled~ Does CSVIter not support shuffle mode?

Thanks ^_^

**Comment by tqchen** [comment]
CSVIter currently do not support shuffle, mainly because it does not assume things can be loaded into memory

**Comment by jmschrei** [comment]
Is it possible to raise a Warning if shuffle is set to True, then?

**Comment by tqchen** [comment]
This is rooted into whether we are able to report unknown parameters in IOIter.

It is a bit hard in current case, mainly because the real iterator is nested combination of several iterators, with each take part of the parameters. An error will be raised for other cases, such as operators when wrong parameter is presented.
