### ISSUE TITLE
How to extract feature maps from multiple layers?

### ISSUE THREAD

**Issue by nicklhy** [dmlc/mxnet#1636]
Hi~
I need to extract some feature maps from my trained networks. I have read the code in https://github.com/dmlc/mxnet/blob/master/example/notebooks/predict-with-pretrained-model.ipynb that I need to get the feature layer symbol out of internals and create a new model by using original model parameters.
But here is my question: do I need to create N models and run the forward process like "global_pooling_feature = feature_extractor.predict(batch)" for each of them to get N feature maps from different layers? Is there a way that I can get them all within a single forward process?

**Comment by piiswrong** [comment]
get_internals gives you all internal features.
You can also use mx.sym.Group to group multiple symbols.
The output will have multiple ndarrays

**Comment by nicklhy** [comment]
Thanks!

**Comment by lzx1413** [comment]
I run this code
``` python
print im.shape
from collections import namedtuple
Batch = namedtuple('Batch', ['data'])
mod.forward(Batch([mx.nd.array(im)]))
prob = mod.get_outputs()[0].asnumpy()
all_layers = mx_symbol.get_internals()
all_layers.list_outputs()[0:10]
```
and there is the result
```
(1, 3, 335, 500)
['data',
 'conv1a_weight',
 'conv1a_output',
 'bn2a_branch2a_gamma',
 'bn2a_branch2a_beta',
 'bn2a_branch2a_moving_mean',
 'bn2a_branch2a_moving_var',
 'bn2a_branch2a_output',
 'res2a_branch2a_relu_output',
 'res2a_branch1_weight']
```
I still don't know how to get the feature map after conv1a
could anyone give me a help on this? thanks

**Comment by futurely** [comment]
https://github.com/dmlc/mxnet/search?utf8=%E2%9C%93&q=get_internals

**Comment by coolbrain** [comment]
@piiswrong  There is no problem when I use mx.sym.Group to extract feature maps from multiple layers in testing, but it has problems when use it in training. The error is like this:

mxnet.base.MXNetError: [16:11:49] src/executor/graph_executor.cc:50: Check failed: i < head_grads.size() && !head_grads[i].is_none() Because the last operator is not Loss function, head_gradient is required when calling backward. If you are attempting to minimize the output as an objective, please modify your network and pass it through the make_loss symbol.

so I use get_internals to  get internal features, but the return is object of Symbol. I want to get the Ndarrays of feature maps from multiple layers in training time. How can I use these API to get that?

**Comment by ysfalo** [comment]
@coolbrain try mx.sym.BlockGrad(feature_symbol)

**Comment by zhanghongjie101** [comment]
@ysfalo It will get 'ValueError: Shape of labels 1 does not match shape of predictions 2'
