### ISSUE TITLE
grad_req has no 'add' option for FeedForward Model API both in python and R

### ISSUE THREAD

**Issue by ziyeqinghan** [dmlc/mxnet#1715]
Recently I am reading the implementation of LSTM in python and want to implement LSTM in both the low-level interfaces and FeedForward model in R. 

I read the example `lstm_ptb_bucketing.py` and find that it uses the FeedForward model to train the LSTM network. However, current FeedForward model only use the default 'write' for `grad_req` parameter when binding the symbol. This is incorrect since the weights in RNN model are shared across time, thus the `grad_req` should be set as 'add'.

I think we need to modify the FeedForward model interface, such as by passing a parameter to specify whether to use 'add' for `grad_req`. The same problem also exists in the R package. 

@pluskid @thirdwing

**Comment by pluskid** [comment]
Using `add` for `grad_req` means you want the accumulation to be added across different forward-backward pass (e.g. when you implement BPTT manually). For the unrolling case, grad sharing is handled internally automatically since the weights are shared by construction. There is no need to use `add` for `grad_req` in this case.

**Comment by ziyeqinghan** [comment]
@pluskid I got it. Thank you so much!
