### ISSUE TITLE
error when compile with " USE_DIST_KVSTORE = 1 "

### ISSUE THREAD

**Issue by Ldpe2G** [dmlc/mxnet#1870]
when I compile MXNET with the USE_DIST_KVSTORE set to 1 in config.mk file, I got the following error message: 

include/mxnet/kvstore.h:172:32: error: ‘ps::Environment’ has not been declared
...

Anyone knows why?

thanks

**Comment by xldrx** [comment]
Same problem here

**Comment by ranxian** [comment]
This might because the ps-lite in the gitsubmodule is not update to date with https://github.com/dmlc/ps-lite. The gitsubmodule has is on (7faaeb73bcb9d68b464186d3191494aa95243703) while the head is on (8aff164580f0e4ff81ad98038b6ec4ec02452ce8)

Just update ps-lite by pulling from the master branch can solve this problem

**Comment by Ldpe2G** [comment]
thanks @ranxian I will try.
