### ISSUE TITLE
Why `_power` is underlined

### ISSUE THREAD

**Issue by hotpxl** [dmlc/mxnet#1944]
Is there any reason in `src/operator/elementwise_binary_op-inl.h`, all functions starts with an underscore? I would expect the function names to be compatible with NumPy.

Also, can we have a logarithm since we already have a power?

**Comment by tqchen** [comment]
power is underscored because it only takes two ndarray as input, there are other two functions, _power_scalar, _rpower_scalar that defines power over scalar. So overriding in language native side is needed.

log is already defined https://github.com/dmlc/mxnet/blob/master/src/operator/elementwise_unary_op-inl.h#L127

**Comment by hotpxl** [comment]
I see. So we should really have some kind of "dispatch" function that calls corresponding implementation.

Or can we have a "broadcast" behavior by default just like numpy ufunc?

**Comment by tqchen** [comment]
Yes,currently we need somekind of dispatch function for this. For power, as we have to do operator overloading anyway, so it is fine.
