### ISSUE TITLE
example about doing OCR use CNN+RNN

### ISSUE THREAD

**Issue by xlvector** [dmlc/mxnet#2018]
I see some papers about doing OCR without segmentation using CNN and LSTM.

Does mxnet support such work?

**Comment by piiswrong** [comment]
I don't think we have an example for this. But you can definitely do it with mxnet. The speech and RNN examples are good references

**Comment by xlvector** [comment]
Thanks!

**Comment by sinmaystar** [comment]
@xlvector 
Have you succeeded in achieving CNN + LSTM + CTC code?
or just achieve example warpctc?
recently I am studying cnn + lstm + ctc joint-training, but I have met some problem, did you make it successfully?

**Comment by xlvector** [comment]
You can see examples under /examples/warpctc/

**Comment by sinmaystar** [comment]
This example does not use cnn to extract features as lstm's input，so when the captcha have rotate or some change it wont recognize success，do u plan to add cnn to this example？
            在2016年07月20日 15:17，Xiang Liang 写道:You can see examples under /examples/warpctc/

**Comment by sosong** [comment]
@sinmaystar @xlvector Do you gays make some progress with cnn+rnn+ctc?

**Comment by xlvector** [comment]
example/warpctc  @sosong   You need to use an old version of warpctc from https://github.com/baidu-research/warp-ctc with version 5bfb46e83bcb338a09fbf875cb0b02bc39746b36

**Comment by xinghedyc** [comment]
@xlvector Does warp-ctc plugin support bucketing? I implemented cnn-bi_lstm-ctc with buckets in order to fit variable input image length, but I find it all the outputs of final layer remain same during training, however it will converge if I resized all images to fixed length and only use one bucket.
So I guess warp-ctc may not be compatible with bucketing.
