### ISSUE TITLE
lstm model save, load, predict produces errors:"Input node is not complete"

### ISSUE THREAD

**Issue by gleery** [dmlc/mxnet#2217]
I run the example codes in rnn/lstm_bucketing.py,  and I try to save/load the model, then call the predict method, which gives me "Input node is not complete" error.

The provided_data looks like this:
{'l0_init_h': (32, 200), 'l0_init_c': (32, 200), 'data': (32, 60), 'l1_init_c': (32, 200), 'l1_init_h': (32, 200)}

and model.symbol.list_arguments() prints:
['data', 'embed_weight', 'l0_i2h_weight', 'l0_i2h_bias', 'l0_init_h', 'l0_h2h_weight', 'l0_h2h_bias', 'l0_init_c', 'l1_i2h_weight', 'l1_i2h_bias', 'l1_init_h', 'l1_h2h_weight', 'l1_h2h_bias', 'l1_init_c', 'cls_weight', 'cls_bias', 'softmax_label']

the input data seems to be complete, can you help point out where the error is? thanks.

**Comment by gleery** [comment]
I figured out that the direct reason is because in lstm_unroll function, 
```
label = mx.sym.transpose(data=label)
label = mx.sym.Reshape(data=label, target_shape=(0,))
sm = mx.sym.SoftmaxOutput(data=pred, label=label, name='softmax')
```
the label is processed as the code above, which makes mxnet graph engine think the label variable becomes an input variable.
I tried to add a fake 'softmax_label' variable to provide_data, which pass the infer_shape function, but still results in another error,

>     outputs = [np.concatenate(x) for x in output_list]
> ValueError: need at least one array to concatenate

the output_list is empty which should contains the softmax_label as output.
Not knowing how to make it work.

**Comment by pluskid** [comment]
@gleery Which `lstm_unroll` are you using? Yes there is a potential issue, if you are using [the one in ptb rnn example](https://github.com/dmlc/mxnet/blob/master/example/rnn/lstm.py#L48), because that example applied transformation to the labels. So you will need to provide (fake) label shapes to make it work. This is inconvenient, we will need to refactor it, but if you want to know, [the lstm_unroll in speech demo](https://github.com/dmlc/mxnet/blob/master/example/speech-demo/lstm_proj.py#L53) solved the problem. 

For the error in `prediction`, if you are using bucketing, make sure to set `merge_batches=False` when calling prediction. Because if different batches are of different shape, then it is impossible to merge them. Please see [the doc](http://mxnet.readthedocs.io/en/latest/packages/python/module.html#mxnet.module.base_module.BaseModule.predict) for more details.

**Comment by gleery** [comment]
thanks, the speech demo is helpful, I will read it first.
