### ISSUE TITLE
Getting Started Example [MNIST] returns error [R]

### ISSUE THREAD

**Issue by SplashDance** [dmlc/mxnet#2270]
I tried following the MNIST example but when I create the **train** and **val** datasets I get this error:

> rsession(13325,0x7fff7bee6300) malloc: *** mach_vm_map(size=7037526865735659520) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Error: std::bad_alloc

Note: This error occurs when I try to run the script on a MBP running Yosemite. However, on an older computer running Mavericks this error does not occur.

**Comment by SplashDance** [comment]
### Update

I think the problem is that my browser automatically uncompressed the files when I downloaded them. Although this issue is addressed on the **MNIST** webpage, the proposed solution (remove the **.gz** file extension) didn't seem to fix the issue with **mxnet**. If this issue can't be fixed on your end than it would probably be helpful to mention it somewhere in the tutorial just give people a heads-up about it.

Thanks,
Steve

**Comment by thirdwing** [comment]
I think you should uncompress the data set first.

You met the error when running the `mx.io.MNISTIter` code?

**Comment by thirdwing** [comment]
BTW, the correct message you should get is like

```
> train <- mx.io.MNISTIter(
+   image       = "train-images-idx3-ubyte",
+   label       = "train-labels-idx1-ubyte",
+   input_shape = c(28, 28, 1),
+   batch_size  = 100,
+   shuffle     = TRUE,
+   flat        = TRUE
+ )
[23:05:25] src/io/iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(100,784)
```

**Comment by thirdwing** [comment]
Closing this right now. Feel free to reopen.

**Comment by jdhao** [comment]
I have also met this problem when I try to get an iterator following the [documentation of MNISTIter](http://mxnet.io/api/python/io.html#mxnet.io.MNISTIter). 

The code I used was:
```
import mxnet as mx

train_iter = mx.io.MNISTIter(image='./train-images-idx3-ubyte.gz',
        label='./train-labels-idx1-ubyte.gz',
        batch_size=16)
```
But I got the following error message:
>terminate called after throwing an instance of 'std::bad_alloc'
> what():  std::bad_alloc
>Aborted (core dumped)

At first I thought it was because the batch_size was too large, so I set a smaller batch_size. I still got the same error.

After reading this issue,  I realize that the MNIST data should be uncompressed first. 
After uncompressing the data, I run the following code:
```
import mxnet as mx

train_iter = mx.io.MNISTIter(image='./train-images-idx3-ubyte',
        label='./train-labels-idx1-ubyte',
        batch_size=16)
```
Then, everything is fine.  The output message is like this:
>[10:40:49] src/io/iter_mnist.cc:94: MNISTIter: load 60000 images, shuffle=1, shape=(16,1,28,28)

I think there is some ambiguity  for the parameter `image` and `label` in the [documentation of the MNISTIter](http://mxnet.io/api/python/io.html#mxnet.io.MNISTIter).  It would be clearer to state that the data and label of MNIST dataset should be uncompressed first before used by MNISTIter.
