### ISSUE TITLE
BucketModel predict

### ISSUE THREAD

**Issue by MonkeyTang** [dmlc/mxnet#2289]
Hello, I use bucketmodel for variable length squence, I have train a model(batch size is 50), but when I want forward, I can't change the batch size(For example, I want batch size is 1). How can I do it?

**Comment by piiswrong** [comment]
@pluskid

**Comment by pluskid** [comment]
@MonkeyTang Yes currently the batch size cannot be changed even between different buckets due to an implementation limit that seem to be easy to change (see [here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/executor_manager.py#L302), where the slices for data-parallelism is pre-computed and re-used for all buckets, so all of them must have the same batch size). Can you describe your use case? Do you need different batch size for training and testing? Or you need different batch size even during only the training stage?

**Comment by MonkeyTang** [comment]
Thank you, I need different batch size for training and testing, the batch size of training is same.

**Comment by pluskid** [comment]
@MonkeyTang OK, then it is an easy case: you can just force rebind the module. And thanks for fixing the bug. Since it seems that you are now able to get it working properly, I am closing this issue. Please feel free to reopen this if needed. Thanks again!
