### ISSUE TITLE
bug in symbol_resnet.py

### ISSUE THREAD

**Issue by XHUJOY** [dmlc/mxnet#2354]
A bug about the TODO in mxnet/example/image-classification/symbol_resnet.py

A BatchNorm layer should follow  "shortcut = mx.symbol.Convolution(...)" in line 97, the kernel size maybe can be changed to (1, 1).

**Comment by Answeror** [comment]
Because we use type A projection[1], which don't have learnable parameter, we a following BatchNorm is unnecessary. Facebook's implementation confirms it [2].
I've also tried type B projection [1], which is performs better than type A projection with 1x1 kernel (see the code comments in #2046). In this case, a following BatchNorm helps.
For the kernel size issue, I've do some experiments using 2-GPU in #2327 and #2366. It shows that the batch size affect the accuracy greatly. Maybe a smaller batch size works with 1x1 kernel, but I didn't do comprehensive experiments about it.

[1] He, Kaiming, et al. "Deep Residual Learning for Image Recognition." arXiv preprint arXiv:1512.03385 (2015).
[2] https://github.com/gcr/torch-residual-networks/blob/master/residual-layers.lua
