### ISSUE TITLE
RNN lstm_unroll seems odd

### ISSUE THREAD

**Issue by freddycct** [dmlc/mxnet#2430]
I have been looking at the lstm_unroll function in examples/rnn/lstm.py

I noticed that there is only **one** mx.sym.SoftmaxOutput connected at the end. However, I thought RNN should have a mx.sym.SoftmaxOuput at every time step.

It seems that prediction only happens at the last time step. I thought that the output of every lstm is fed as input to the next lstm cell according to the char-rnn ipython notebook tutorial. In this case, how does all this work when there is only 1 SoftmaxOuput at the last time step. 

I must say, this RNN implementation in MXNet seems very mysterious to me.

**Comment by sxjscience** [comment]
@freddycct This is an implementation for the language modelling task **without** Scheduled Sampling(https://papers.nips.cc/paper/5956-scheduled-sampling-for-sequence-prediction-with-recurrent-neural-networks.pdf). The ground truth word rather than the prediction output is used as the input of the next timestamp. Since the outputs are generated without predictions, we can just concatenate predictions from all the timestamps and fit them into a single loss layer.

**Comment by freddycct** [comment]
Oh I see, in that case I have to add the softmaxoutput to each lstm cell. I see, thanks

**Comment by sxjscience** [comment]
@freddycct That's great! You are more than welcome to give an example on that!

**Comment by sxjscience** [comment]
@freddycct Close this issue and you can submit a PR when you get some examples.
