### ISSUE TITLE
About training accuracy

### ISSUE THREAD

**Issue by fhowen** [dmlc/mxnet#269]
Hi，
I use Alexnet.py in /example/imagenet to training with the configure unchanged,but after 20 rounds ,the accuracy is only 0.438870,much worse than the result shown in the docs(81%).
the dataset is from imagenet.
I wonder where this difference comes from.
Any help?
Thx.

**Comment by antinucleon** [comment]
1. The script is not a full script to train an AlexNet, because to train an AlexNet you need to reduce learning rate after several round
2. Please note 81% is top-5 accurate, and ```43.8``` is top-1 accurate. In my memory, when top-1 accuracy reach 55%, it is almost 81%.
3. What you need to do is stop current training now, load params from current checkpoint, then start train with learning rate of 0.001. After accuracy stops growing, switch to 0.0001

**Comment by fhowen** [comment]
Thanks,I will try it.
