### ISSUE TITLE
Set begin_round when retrain the model

### ISSUE THREAD

**Issue by ommiissyu** [dmlc/mxnet#279]
hi, all

I am using mxnet to train the model. I found that when we train the model from the checkpoint, the begin_round is always set to 0. 
Maybe we should reset the begin_round when we load a model from a checkpoint.

**Comment by tqchen** [comment]
Thanks for pointing this out. I guess this can be done by adding a begin_round parameter to FeedForward. Are you interested in open a PR or this?

**Comment by pluskid** [comment]
I think ideally we should save the state of the solver (e.g. current epoch) into checkpoint file. And when loading from checkpoint, automatically recover the state.

**Comment by tqchen** [comment]
Currently the checkpoint only contains the symbol and the ndarrays. To save additional state, 

- we can either support saving of json string in the ndarray file(so saving anything that can be serialized into json). 
- Or use a special ndarray(epoch) to store the value.

The later probably needs less change.  I think we need to think a bit about this, since this trade simplicity of checkpt vs usability.

**Comment by pluskid** [comment]
One possible choice is to rely on language specific serialization technique to save extra solver state. It should be fairly easy to implement, but for that part of data it is no longer possible to, say save in Python and then load in Julia. Though I think most of the time, people won't do this "multi language training". And since we are implementing solvers in the specific script languages, each of them might have their own specific states that need to save and load, due to slight different implementation or language differences.

**Comment by pluskid** [comment]
I think at least in the long run we need to adopt more general ways here if we want to support restarting of any optimizers, including user-defined optimizers. Either to recover from a crash or to allow the user to explicitly run training again but for a more number of epochs.!

**Comment by tqchen** [comment]
Fixed by #298 close this issue for now
