### ISSUE TITLE
Cache the compiled computation graph

### ISSUE THREAD

**Issue by futurely** [dmlc/mxnet#282]
Unlike what [the programming model document](http://mxnet.readthedocs.org/en/latest/program_model.html) said about Chainer, it actually also uses the symbolic programming technique. The compilation steps are usually very slow, so it caches the compiled computation graphs to files. It may take some time to compile for the first time, but later running will be much faster.

http://chainer.readthedocs.org/en/latest/cupy-reference/overview.html?highlight=cache
http://chainer.readthedocs.org/en/latest/tips.html?highlight=cache
https://github.com/pfnet/chainer/pull/266

**Comment by tqchen** [comment]
Thanks for pointing it out. This seems to mean chainer caches the kernels during compilation. Which is the individual operators. This is different from what was discussed in the note.

Having a computation graph is not restricted to programming styles(i.e. symbolic programs). In order to get gradient, imperative style program also need to track the computation graph. The difference is the restrictions on how each programming style can act on the graph

The nature of having to be ```prepared for possible futures```` applys to imperative style programs, however. Which leads to things such as not being able to recycle memory even when user only want forward pass, and not being able to share memories, because user might reference them in future.

**Comment by futurely** [comment]
I understand the difference between the two styles. This issue came to my mind when I was reading the [Model Checkpoint](http://mxnet.readthedocs.org/en/latest/program_model.html#model-checkpoint) section. In the following snippet, only the computation graph is saved. After loading it back, it is compiled. Can the compiled `f` be saved too so that it can be loaded directly next time as well as the graph?
```
A = Variable('A')
B = Variable('B')
C = B * A
D = C + Constant(1)
D.save('mygraph')
...
D2 = load('mygraph')
f = compile([D2])
# more operations
...
```

**Comment by tqchen** [comment]
Oh, i see. We did not meant to mean compilation cost in this section, but simply mean being able to save/load a model.  We did not intend to discuss the computation caching here.

You are right that caching a compiled graph might speedup things.  The compilation overhead depends on the implementation, the optimization carried etc. It also means the engineering overhead to implement optimizations. 

You are more than welcomed to open a pull request to share your ideas as well :)

**Comment by futurely** [comment]
According to the Amdahl’s law metioned in the document, only performance critical parts should be optimized. @joschu benchmarked the compilation time of CGT and Theano in "[Announcing CGT](http://joschu.github.io/)". A similar benchmark is needed before actually doing the optimization.

**Comment by tqchen** [comment]
Yes, you are right. I a smartly chosen compilation strategy(that avoid complicated searches) might not be that slow as people thought.
