### ISSUE TITLE
Improve the speed of im2rec with multi-threading

### ISSUE THREAD

**Issue by futurely** [dmlc/mxnet#288]
Single-threaded processing is too slow. It may take much longer time to prepare the dataset than to train a model on it.

**Comment by antinucleon** [comment]
The bottle neck is random seek on HDD, so single thread is enough on HDD

**Comment by tqchen** [comment]
You can pack the dataset distributedly on multiple machines by splitting the data-set into independent lists, pack them into multiple rec files.

The file path accept path to the rec, and will load through all the rec files by default

**Comment by futurely** [comment]
The I/O and computation can be run in parallel with a graph like ImagePrefetching -> Transformation -> BufferedRecordSaving.

**Comment by antinucleon** [comment]
Buffer one round usually costs 8-10 hour for ImageNet, while AlexNet is
less than an hour, so parallel is not a good choice. And once you buffered
it, you can reuse every time

**Comment by tqchen** [comment]
The major reason was the bottleneck of small image open and reading, which creates a lot of overhead.
This is capped by the filesystem. Because transforming is not bottleneck here. It is likely we don't gain much (still caped by the image loading speed) by doing a parallel pipeline. This was quite unfortunate, but is the major reason why we want to pack the images before use. 

To speed things up, running packings from multiple machines, or simply multiple disks(so the image reading can be done in parallel) in parallel should solve the problem.

**Comment by qiaohaijun** [comment]
I will try to split the raw data

**Comment by futurely** [comment]
https://github.com/dmlc/mxnet/pull/1488
