### ISSUE TITLE
Suggestion for asking questions

### ISSUE THREAD

**Issue by jonbakerfish** [dmlc/mxnet#3154]
I think [StackOverflow/tagged/mxnet](http://stackoverflow.com/questions/tagged/mxnet) is a better place for help and support, technical or algorithmic questions. The [Github issues](https://github.com/dmlc/mxnet/issues) should focuses on tracking requests and bugs.

The pros are:
- The "UP/DOWN vote" and "Reputation" mechanisms of SO encourage users/developers to **ask good questions** and attract a wider range of experts to help answer the questions. (e.g. [SO/tagged/tensorflow](http://stackoverflow.com/questions/tagged/tensorflow?sort=votes&pageSize=30))
- The rewards of reputation in SO can motivate users/developers to help others, and there is a higher chance for a question **being answered**.
- The search experience of the existing answers to previous asked questions is better on SO. 
- Reduce the number of "issues".

**Comment by albertyou2** [comment]
The link you given is dead.

**Comment by minazou** [comment]
You suggestion sounds good, but I have 2 comments about it.

1. Most of questions on stackoverflow are not answered correctly, because there are few people focusing on mxnet. Questions in github issues are the same, though there are much more people than stackoverflow. I think it's better to make mxnet community more active first rather than separating questions.
2. Compared to tensorflow, mxnet is lock of documentation and nice example/tutorial, so many people don't know how to use it.
 If you are an engineer, you may realize how it works by tracing code. But, if you are just a data scientist, you may not comprehend mxnet in detail.

So, we may do following to solve your problem.
- Answer the problem(not issue) as possible.
- Suggest people to post question on stackoverflow in the same time.
- Help mxnet fill the documents/tutorials.
