### ISSUE TITLE
OpenCL support?

### ISSUE THREAD

**Issue by zachmayer** [dmlc/mxnet#328]
Not all of us have NVIDA GPUs =D

**Comment by tqchen** [comment]
This was rooted deeply into OpenCL support for mxnet. It is hard for short term, mainly due to the lack of support of template programming in current opencl, which makes it hard for https://github.com/dmlc/mshadow to compile on OpenCL.

There is a future proposal of enhancing opencl with c++(11) features. I think things will become more natural after that

**Comment by zachmayer** [comment]
Awesome, thank you
