### ISSUE TITLE
minor refactor of dag_engine.h 

### ISSUE THREAD

**Issue by mli** [dmlc/mxnet#40]
there are some suggestions potentially to make DAGEngine more readable:
```
(Variable, OprHandle) -> (VarPtr, OprPtr) or (VarHandle, OprHandle)
(use_var, mutate_var) -> (const_var, mutable_var) or (read_var, write_var)
(NewVar, NewOperator) -> (NewVar, NewOpr) or (NewVariable, NewOperator)
```
i'm not too sure about the following two 
```
(DeleteOperator, PushDelete) -> (DeleteOpr, DeleteVar)
(Var, Opr, Fn) -> (Var, Oper, Func)
```

do we need both `Push(Fn exec_fun)` and `PushAsync`? it looks like we can always first `NewOperator` and then `Push(OprHandle)`

**Comment by hotpxl** [comment]
I think the suggestions are good. One thing about `mutate_var` is, even if you need to READ and WRITE a variable, you should not put it into `use_var` once it's in `mutate_var`. The name `const_var` and `mutable_var` would be better in this sense.

`PushAsync` pushes a temporary operator. It's needed because I use it to delete an operator.

**Comment by mli** [comment]
got it, so the difference is that 

the user need to delete the op in `Create & Push(op)`, while the system managers the op in `Push/PushAsync(func)`? i'm fine with that. another solution maybe always return `std::shared_ptr<OprHandle>`

**Comment by hotpxl** [comment]
Yes.

We actually have to do some work (push `OprHandle` into queue) before destructing it. So a destructor would not meet the needs.

**Comment by hotpxl** [comment]
Also renaming `DAGEngine` to `Engine`, in case I forget.
