### ISSUE TITLE
MXNet for R on Windows installation fails due to latest update in DiagremmeR

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [dmlc/mxnet#4527]
More details here on stackoverflow - http://stackoverflow.com/questions/41469083/install-error-on-mxnet

**Temp fix**
- Update installation instruction to reflect this issue. This alteast helps new users to know the cause of issue and downgrade their DiagremmeR package.

**Further**
- We need to work on the compatibility issue.
- We should check if we need to add mxnet as reverse dependency to DiagremmeR - https://cran.r-project.org/web/packages/DiagrammeR/index.html

**Comment by piiswrong** [comment]
@miguelgfierro @thirdwing

**Comment by thirdwing** [comment]
The update of `DiagremmeR ` broke several pkgs including `xgboost`.

**Comment by Roshrini** [comment]
@thirdwing 
Today I tried to run r-installation script on ubuntu.
https://github.com/dmlc/mxnet/blob/master/setup-utils/install-mxnet-ubuntu-r.sh

Received the same error and installation failed.
Error : object ‘combine_edges’ is not exported by 'namespace:DiagrammeR'
ERROR: lazy loading failed for package ‘mxnet’

 To solve it, I had to installed older version of DiagrammeR and then, it worked completely fine.

wget http://cran.us.r-project.org/src/contrib/Archive/DiagrammeR/DiagrammeR_0.8.1.tar.gz
sudo R CMD INSTALL DiagrammeR_0.8.1.tar.gz

So, seems like this issue is not yet resolved completely.

**Comment by thirdwing** [comment]
Please update your repo. All usage of `combine_edges` has been removed.

**Comment by studentdave** [comment]
error still seems to be there:
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("mxnet")



> install.packages("drat", repos="https://cran.rstudio.com")
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/drat_0.1.2.tgz'
Content type 'unknown' length 51508 bytes (50 KB)
==================================================
downloaded 50 KB


The downloaded binary packages are in
	/var/folders/2x/31fvjwkx7kg2j666w74phrlw0000gn/T//RtmpcIWKqD/downloaded_packages
> library(drat)
> drat:::addRepo("dmlc")
> 
> 
> install.packages("mxnet")
trying URL 'https://dmlc.github.io/drat/bin/macosx/mavericks/contrib/3.3/mxnet_0.7.tgz'
Content type 'unknown' length 2966210 bytes (2.8 MB)
==================================================
downloaded 2.8 MB


The downloaded binary packages are in
	/var/folders/2x/31fvjwkx7kg2j666w74phrlw0000gn/T//RtmpcIWKqD/downloaded_packages
> 
> library(mxnet)
Error : object ‘combine_edges’ is not exported by 'namespace:DiagrammeR'
Error: package or namespace load failed for ‘mxnet’

**Comment by thirdwing** [comment]
@starimpact 

The error is due to the update in `DiagrammeR`. It breaks many packages including `mxnet` and `xgboost`.

I have updated the related code. However, I don't have access to any Windows machine now, so the Windows pkg hasn't been updated. Please try to install the old version of `DiagrammeR`.

```r
require(devtools)
install_version("DiagrammeR", version = "0.8.1", repos = "http://cran.us.r-project.org")
```

**Comment by studentdave** [comment]
ah, yes that seemed to fix the, library(mxnet) loading error! thx u!

**Comment by dma100180** [comment]
Hello, everything was fine with MXNET and an update has caused me to change the diagrammer.
I fixed it with:

require (devtools)
install_version ("DiagrammeR", version = "0.9.1", repos = "http://cran.us.r-project.org")

a greeting
