### ISSUE TITLE
does the LSTM networks support multi-gpus?

### ISSUE THREAD

**Issue by yuzcccc** [dmlc/mxnet#476]
I try to directly modify the first input arg. of lstm.setup_rnn_model:  mx.gpu()-> gpus=[mx.gpus(i) for i in range(num_gpues)], which seems does't work..

besides, could some more examples of lstm such as image(video) caption been provided?

**Comment by antinucleon** [comment]
Currently the example doesn't support multi-GPU. We hope to settle down a general RNN model soon, which will handle multi-GPU easily like FeedForward models. 

Currently there is no caption example, but I don't think it is far from it :）

**Comment by pluskid** [comment]
@antinucleon I think it might be possible to use the built-in `FeedForward` to train the LSTM example once #468 is merged, by providing a customized data iter that produce inputs from text (and also initial zero states for sequence beginning). Because we explicitly unroll the network and use a fixed sequence length. It looks exactly like a simple feed forward network. But for more general case, we still need to build explicit RNN interface.

**Comment by tqchen** [comment]
this is enabled by #690
