### ISSUE TITLE
[Discussion] Implement LSTM training utilizing High level API (mx.model.FeedForward)

### ISSUE THREAD

**Issue by XericZephyr** [dmlc/mxnet#547]
I am considering a new example of LSTM using the high level API, which can easily benefit from the distributed training. However, the LSTM model and the optimization technique might require a more general model programming prototype, part of my suggestions are: 

1. Adding `epoch_start_callback` and `batch_start_callback`. This might help us to transfer the previous LSTM cell states to the LSTM cell in the next batch. Also we can reset the hidden states at the beginning of each epoch. 

2. The shape infer only considers the input shape. Sometimes it might also need to consider the input from last batch or so. So I might need suggestions in developing this part, to be more specific, how to hack `_init_param` to be more generic?

**Comment by piiswrong** [comment]
I wrote a model base class and a solver base class for autoencoder training under example/autoencoder/model.py & example/autoencoder/solver.py 
You can have a look.
It also supports printing internal activation for debugging

**Comment by pluskid** [comment]
There is [an implementation of char-rnn LSTM](https://github.com/dmlc/MXNet.jl/tree/master/examples/char-lstm) in the Julia binding using the high-level API `FeedForward`. The trick is:

To provide explicitly the init states from the data provider, so that shape inference becomes possible. Because we are dealing with fixed length sequence and explicit unrolling, those init states are just constant zero blobs, so there is no need to use callbacks to reset them.

**Comment by pluskid** [comment]
But I agree that to support more general RNN with variable sequence length and avoid explicit unrolling, we might need to extend the current shape inference mechanism to support *Self-connecting-node* or *Delayed-node*, so that the shape could be automatically inferred. Of course, we will need a new model other than `FeedForward` for more general time-sequence models.

**Comment by XericZephyr** [comment]
@pluskid I have a question. The python code pass the last states into the initial states for each batch. So I think it's probably not ok to just pass zero blobs to init states. I am still working on evaluating the effect of this behaviour.

**Comment by pluskid** [comment]
The state is reset after gradient update, and gradient update is done every batch by default.

Even if you want to copy over the states, that could be done, see for example the sampler example in Julia.

**Comment by pluskid** [comment]
Was too brief because I was one a phone. I looked at the python lstm example again. You are right, it seems the states are copied over during the whole epoch. The forward states are transferred even if the backward is cut by resetting the gradient. If you want to achieve this with high-level API, it is still possible by having the last states in the LSTM output, and copying that over in the data iteration. See [the Julia sampler](https://github.com/dmlc/MXNet.jl/blob/master/examples/char-lstm/sampler.jl#L58) for example.

But I think this is pretty much what you could achieve without extending a lot the current feedforward API. For more flexible LSTM/RNN, I think a separate model should be built.

**Comment by XericZephyr** [comment]
Yes. I agree. Currently, building a separate model is a good(probably the best) idea. However, it cannot easily utilize the multi-GPU and distributed training benefit. Sigh. It's very hard to choose.

**Comment by pluskid** [comment]
just FYI, the current [bucketing RNN example](https://github.com/dmlc/mxnet/blob/master/example/rnn/lstm_ptb_bucketing.py) is using high-level API.
