### ISSUE TITLE
How to understand terms "kNCHW", "NCW", "NCHW", "NCDHW", "kNHWC"...

### ISSUE THREAD

**Issue by kernel8liang** [dmlc/mxnet#5778]
How to understand terms "kNCHW", "NCW", "NCHW", "NCDHW", "kNHWC", "kNCHW", "kNHWC".

Totally， lost.

**Comment by ZihengJiang** [comment]
The capital letter is used to specify the layout of data, which is used in convolution usually:
N: batch size
C: channel
H: height
W: width

so that "NCHW" means a data whose layout is `(batch_size, channel, height, width)`
and the lower case `k` represents a enum class, see: https://github.com/dmlc/mshadow/blob/master/mshadow/base.h#L312
https://github.com/dmlc/mxnet/blob/master/include/mxnet/operator.h#L24

**Comment by sxjscience** [comment]
We need to document the behavior of layout.

**Comment by kernel8liang** [comment]
Why "batch size" is  N, and "k" represents "a enum calss" ?

**Comment by ZihengJiang** [comment]
@kernel8liang just custom, which is also common in other librarys

**Comment by ZihengJiang** [comment]
@sxjscience a FAQ pinned issue in github maybe also good

**Comment by kernel8liang** [comment]
thanks.
