### ISSUE TITLE
Piecewise constant functions

### ISSUE THREAD

**Issue by patwa67** [dmlc/mxnet#5927]
I have input data that take the form X_i,j = {0,1 or 2} and a continuous output Y_i. Is there some way to model piecewise constant functions in mxnet?

**Comment by jmacglashan** [comment]
Create logical masks, and multiply them by the chosen output for that logical condition, and then add them all together.

For example, suppose you want
```
y = 10   if x = 0
    -4.2 if x = 1
    14   if x = 2
```

Then in mxnet
```
x = mx.sym.var('x')
y = 10 * (x == 0) + -4.2 * (x == 1) + 14 * (x == 2)
```

This works because mxnet's logical operators return numeric 1/0 values (rather than boolean values). Consequently, each term in the above expression will be zero *except* the condition matching the value of x. So if x = 1, then the result of that operation is: `10 * 0 + -4.2 * 1 + 14 * 0 = -4.2`.

Same of course works if you're using mxnet ndarrays.

**Comment by patwa67** [comment]
OK, my intention is to estimate the mean of each constant. The data has many variables p in x
```
y    x[,1]    x[,2]    ...    x[,p]
10    0        1       ...     2
-4.2  1        1       ...     1
8.5   0         0       ...     1
-1    1         1       ...     2
5.9   0         2       ...     0
0.5   2         2       ...    1
```

Any suggestions how to deal with that? My first goal is simply to model as a linear regression.

**Comment by jmacglashan** [comment]
If I'm understanding you, I would just restructure your data to be binary inputs which is far more standard for this kind of setup than special cases when you might really want to go through the trouble of defining piece-wise functions. 

In the case when you have 1 variable x in {0, 1, 2} then transform your input to be a 1 hot vector. For example, 
`x = 0` becomes `[1, 0, 0]`, 
`x = 1` becomes `[0, 1, 0]`,
`x = 3` becomes `[0, 0, 1]`.

If you have 2 variables, x in {0, 1, 2}^2, then you basically concatenate two one-hot vectors. For example,
`x = [2, 0]` becomes `[0, 0, 1, 1, 0, 0]`,
`x = [1, 2]` becomes `[0, 1, 0, 0, 0, 1]`,
etc.

Extend for x in {0, 1, 2}^p for arbitrary p.

After pre-processing your input in this way, just add a FullyConnected layer to it and your favorite loss function.

You may want to look into using mxnet's [one_hot](http://mxnet.io/api/python/symbol.html#mxnet.symbol.one_hot) function for helping with the pre-processing (or you can do it manually pretty easily), possibly with a reshaping afterwards.
