### ISSUE TITLE
[Discussion, Python] Eliminating Arguments of Model API

### ISSUE THREAD

**Issue by XericZephyr** [dmlc/mxnet#609]
Currently, there are too many arguments of model API in Python, making it extremely hard to maintain the code. 

Can we find out a way to eliminate them? Or, in a better word, better organize them?

**Comment by pluskid** [comment]
Are you talking about a better way to organize them or actually find some way of *removing* some of the arguments?

**Comment by XericZephyr** [comment]
Sorry for the confusion. @pluskid   I am talking about better organizing them and hope to hear some suggestions from you. 

I think reasonably eliminating some of them might be a way to better organize the arguments. 

There are absolutely other ways, some of them coming out of my mind like: 

* Grouping the callbacks into one argument, with namedtuple. For example, when accessing callbacks, using `callback['batch_end_callback']` or `callback.batch_end_callback` and so.

**Comment by pluskid** [comment]
There is another not-so-cool thing related is that some parameters are passed when constructing the model, while others are passed when calling train. For example, `num_epoch` might better be an argument of `fit` instead of `__init__`. I'm not sure whether it is to keep consistency with the sklearn API or not. But I somehow gave up thinking of doing the refactoring because

- There are many parameters that one cannot avoid, so maybe re-organizing helps a bit, but not much
- Changing this kind of basic API one need to modify almost all the examples and unit-tests

But if you have time to think about it carefully, I tend to encourage you continue to make a proposal with details on how you want to refactor it and people could discuss.
