### ISSUE TITLE
Update ElementwiseScalarOp

### ISSUE THREAD

**Issue by pluskid** [dmlc/mxnet#639]
I find the name and documentation for this argument not very informative. It seems calling `_MinusScalar(sym, scalar=2, scalar_on_right=True)` means `2 - sym`? Then shouldn't the argument be `scalar_on_left`?

**Comment by antinucleon** [comment]
I think so. Default will be left.

**Comment by tqchen** [comment]
I think we need to fix this, rename scalar_on_right->scalar_on_left, and fix this case https://github.com/dmlc/mxnet/blob/master/src/operator/elementwise_binary_scalar_op-inl.h#L139

@yajiedesign

**Comment by tqchen** [comment]
cc @yajiedesign who contributed the elementwise binary op. It is partly due to my uncareful code review.

I think two things need to be fixed

- rename scalar_on_right to scalar_on_left, which is what it really means on code.
- Check https://github.com/dmlc/mxnet/blob/master/src/operator/elementwise_binary_scalar_op-inl.h#L139 , which actually is logic for right operand, and change it

**Comment by yajiedesign** [comment]
https://github.com/dmlc/mxnet/pull/653 change ok
