### ISSUE TITLE
[Vote] Centralized Page for Links of Examples, Apps, Awesomethings

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#670]
Now MX have many examples, mobile and web apps, we need a ***centralized page*** to help user find all these awesome resources(i.e. links to these resources). This is a vote on where to put this page. Please cast vote by reply to this issue

- (1) example/README.md
- (2) mxnet wiki
- (3) doc/awesome-mxnet.md
- (4) a separate repo (dmlc/awesome-mxnet)

**Comment by tqchen** [comment]
@hetong007 @thirdwing @pluskid @mli @antinucleon @piiswrong

**Comment by hetong007** [comment]
I vote for (3) or/and (1). (4) might drive users' attention away.

**Comment by wangg12** [comment]
I vote for a wiki(3) like what torch does.

**Comment by pluskid** [comment]
I vote for (1) and use have some way to automatically be linked in doc (3).

(2) should also be good as it allows other people to edit (?), but I think the main thing should still be (1) or (3) -- just to be consistent with the rest of the documentation system. Otherwise users might get confused. Probably in the main example doc, add pointers to wiki for something like "more examples from the community".

**Comment by pineking** [comment]
I vote for (1).

**Comment by antinucleon** [comment]
vote for 1

**Comment by thirdwing** [comment]
1 or 3

**Comment by mli** [comment]
i'm fine with anyone except for 4. the only problem with 1&3 is that it triggers travis for each edit...

**Comment by tqchen** [comment]
Let us go with 1 then

**Comment by mli** [comment]
i also suggest to clean the current example folder. the purpose of examples are twofold. first it shows how to use mxnet, second it provides simple and clean implementation of algorithms that easy others to do similar works. 

we'd better limit the codes going into this fold, to avoid too frequently commits. so we should merge an example into the master only if 1) it's simple and useful and 2) it's almost well done. but we can refer a link on the readme.md before it's ready to merge.

one can work on an example in two ways:

1. clone mxnet and make a fold under example/
2. a separate repo which requires mxnet is installed on some place, an easy way is `clone mxnet; make; cp -r mxnet/python/mxnet .; cp mxnet/lib/*.so mxnet;`

**Comment by futurely** [comment]
(3) is the best option.

Tensorflow's dedicated website [tensorflow.org](http://tensorflow.org/) is a successful example of attracting a large amount of users in a short time, or to be more specific 13,000 stars, 3,274 forks, 1,296 watches and counting on GitHub in 13 days. Tensorflow keeps the website sources in [a separate directory g3doc](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/g3doc). But it's not clear if the website is hosted on [GitHub pages] (https://pages.github.com/).

**Comment by pluskid** [comment]
@futurely Thanks for the pointer. Though I do not think it is *because* tensorflow has a separate website that it attracts a lot of users.

@mli Is there anything we could do with Travis? It is indeed quite slow currently. Like setting up our own CI server? Or only runs a lightweight subset of tests except, say, it is the first commit of the day or something like that?

**Comment by mli** [comment]
a temp solution is to let the r-test do less iterations. in the future, we can let travis just do unittest, while more the training test on a dedicate (ec2) machine

**Comment by phunterlau** [comment]
I prefer 3 or 4 like this <http://scikit-learn.org/stable/auto_examples/>

**Comment by tqchen** [comment]
updated https://github.com/dmlc/mxnet/tree/master/example
