### ISSUE TITLE
Cannot build with CUDA support on El Capitan

### ISSUE THREAD

**Issue by zmactep** [dmlc/mxnet#728]
Cannot build library with CUDA and cuDNN support on El Capitan. I use latest CUDA Toolkit (7.5) and cuDNN (3.0).

Error is:
```
ld: file not found: @rpath/CUDA.framework/Versions/A/CUDA for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

My config.mk:
```
...

# the additional link flags you want to add
ADD_LDFLAGS = '-L/usr/local/opt/openblas/lib' '-L/opt/cuDNN/lib'

# the additional compile flags you want to add
ADD_CFLAGS = '-I/usr/local/opt/openblas/include' '-I/opt/cuDNN/include'

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA libary to link and compile flag
# if you have already add them to enviroment variable, leave it as NONE
# USE_CUDA_PATH = /usr/local/cuda
USE_CUDA_PATH = /usr/local/cuda

# whether use CUDNN R3 library
USE_CUDNN = 1

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 0

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
USE_BLAS = apple

# add path to intel libary, you may need it for MKL, if you did not add the path
# to enviroment variable
USE_INTEL_PATH = NONE

...
```

**Comment by piiswrong** [comment]
are you using make/os.mk?

**Comment by phunterlau** [comment]
looks like your BLAS is apple but link flag is to openblas which is installed by brew. will it be a problem? maybe you can try `openblas`?

**Comment by leocnj** [comment]
I met the same issue as reported by @zmactep. I changed "USE_BLAS = openblas" and then got the following new error

     ld: library not found for -lopenblas
     clang: error: linker command failed with exit code 1 (use -v to see invocation)

Just FYI: w/o using GPU, I can compile mxnet successfully on Mac OS X 10.11.

**Comment by piiswrong** [comment]
@leocnj you need to install openblas first

**Comment by leocnj** [comment]
@piiswrong I already installed openblas through brew. This is also why I can compile mxnet (only on the CPU running condition) successfully. 

Now, I truly need the function to use GPU to work. Just found a [SO Q/A][http://stackoverflow.com/questions/11632919/cuda-programming-and-xcode] talking about a similar issue. It looks that clang and cuda may have a communication issue. Hope this link will let other folks with more experiences on XCode programming to be able to figure out a solution.

**Comment by zmactep** [comment]
I've attached paths for `openblas` from Homebrew, as I found here: http://www.binwang.me/2015-11-08-install-blas-library-for-mxnet.html. After that I could build the library w/o CUDA support. And now I'm trying to have a GPU version.

@piiswrong yes, I use modified `make/osx.mk`.

**Comment by leocnj** [comment]
@zmactep I reached the same stage as you did - compiling w/o CUDA works. When trying enabling GPU, what kind of errors have you met?  The below is the error I met:

     ld: library not found for -lopenblas
     clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks.

**Comment by zmactep** [comment]
This lines solved my problem:
```
ALL_LDFLAGS += -Xlinker -F/Library/Frameworks -Xlinker -framework -Xlinker CUDA
```

**Comment by leocnj** [comment]
@zmactep I used your line "ALL_LDFLAGS..." but still got the compiling errors. However, I found that changing it to **"ADD_LDFLAGS"** makes the compilation on my MBP successful.

Here is my complete config.mk file, which is based on make/osx.mk and has been expanded based on helpful suggestions here. I am sharing it to facilitate more OSX users to enjoy mxnet. 

```make
#-------------------------------------------------------------------------------
#  Template configuration for compiling mxnet
#
#  If you want to change the configuration, please use the following
#  steps. Assume you are on the root directory of mxnet. First copy the this
#  file so that any local changes will be ignored by git
#
#  $ cp make/config.mk .
#
#  Next modify the according entries, and then compile by
#
#  $ make
#
#  or build in parallel with 8 threads
#
#  $ make -j8
#-------------------------------------------------------------------------------

#---------------------
# choice of compiler
#--------------------
export CC = clang
export CXX = clang++
export NVCC = nvcc

# whether compile with debug
DEBUG = 0

# the additional link flags you want to add
ADD_LDFLAGS = '-L/usr/local/opt/openblas/lib' '-L/usr/local/cuda/lib'

# the additional compile flags you want to add
ADD_CFLAGS = '-I/usr/local/opt/openblas/include' '-I/usr/local/cuda/include'

# per https://github.com/dmlc/mxnet/issues/728#issuecomment-160867057
ADD_LDFLAGS += -Xlinker -F/Library/Frameworks -Xlinker -framework -Xlinker CUDA

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA libary to link and compile flag
# if you have already add them to enviroment variable, leave it as NONE
USE_CUDA_PATH = /usr/local/cuda
# USE_CUDA_PATH = NONE

# whether use CUDNN R3 library
USE_CUDNN = 1

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 0

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
USE_BLAS = apple

# add path to intel libary, you may need it for MKL, if you did not add the path
# to enviroment variable
USE_INTEL_PATH = NONE

#----------------------------
# distributed computing
#----------------------------

# whether or not to enable mullti-machine supporting
USE_DIST_KVSTORE = 0

# whether or not allow to read and write HDFS directly. If yes, then hadoop is
# required
USE_HDFS = 0

# path to libjvm.so. required if USE_HDFS=1
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

# whether or not allow to read and write AWS S3 directly. If yes, then
# libcurl4-openssl-dev is required, it can be installed on Ubuntu by
# sudo apt-get install -y libcurl4-openssl-dev
USE_S3 = 0

```

**Comment by zmactep** [comment]
@leocnj my fault, you are right. I did the same, but have a typo in solution.

**Comment by wanghaisheng** [comment]
why came to "ld: warning: directory not found for option '-L/usr/local/cuda/lib64'" when run  make -j4 
on mac osx 10.11.2 
config
```
#-------------------------------------------------------------------------------
#  Template configuration for compiling mxnet
#
#  If you want to change the configuration, please use the following
#  steps. Assume you are on the root directory of mxnet. First copy the this
#  file so that any local changes will be ignored by git
#
#  $ cp make/config.mk .
#
#  Next modify the according entries, and then compile by
#
#  $ make
#
#  or build in parallel with 8 threads
#
#  $ make -j8
#-------------------------------------------------------------------------------

#---------------------
# choice of compiler
#--------------------
export CC = clang
export CXX = clang++
export NVCC = nvcc

# whether compile with debug
DEBUG = 0

# the additional link flags you want to add
ADD_LDFLAGS = '-L/usr/local/opt/openblas/lib' '-L/usr/local/cuda/lib'  '-L/usr/local/cudnn/lib'

# the additional compile flags you want to add
ADD_CFLAGS = '-I/usr/local/opt/openblas/include' '-I/usr/local/cuda/include'   '-I/usr/local/cudnn/include'

# per https://github.com/dmlc/mxnet/issues/728#issuecomment-160867057
 ADD_LDFLAGS += -Xlinker -F/Library/Frameworks -Xlinker -framework -Xlinker CUDA

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA libary to link and compile flag
# if you have already add them to enviroment variable, leave it as NONE
USE_CUDA_PATH = /usr/local/cuda
# USE_CUDA_PATH = NONE

# whether use CUDNN R3 library
USE_CUDNN = 1

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 0

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
USE_BLAS = openblas

# add path to intel libary, you may need it for MKL, if you did not add the path
# to enviroment variable
USE_INTEL_PATH = NONE

#----------------------------
# distributed computing
#----------------------------

# whether or not to enable mullti-machine supporting
USE_DIST_KVSTORE = 0

# whether or not allow to read and write HDFS directly. If yes, then hadoop is
# required
USE_HDFS = 0

# path to libjvm.so. required if USE_HDFS=1
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

# whether or not allow to read and write AWS S3 directly. If yes, then
# libcurl4-openssl-dev is required, it can be installed on Ubuntu by
# sudo apt-get install -y libcurl4-openssl-dev
USE_S3 = 0

```

**Comment by wanghaisheng** [comment]
according to description https://github.com/BVLC/caffe/issues/1007 here
>Also that warning is a backwards compatibility hack for CUDA 5.5 (?) and earlier versions, after CUDA 6 the 32-bit and 64-bit library files were merged under /usr/local/cuda/lib so you no longer have a /usr/local/cuda/lib64. You can feel free to create a simlink there to point to lib though, to avoid future warnings like this (probably with other code too).

**Comment by chinhiroshi** [comment]
It still does not work.  

NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "__ZTVSt15basic_stringbufIcSt11char_traitsIcESaIcEE", referenced from:
      __ZN4dmlc15LogMessageFatalC2EPKci in ndarray_function_gpu.o
      __ZN4dmlc15LogMessageFatalD2Ev in ndarray_function_gpu.o
      __ZN4dmlc15LogMessageFatalC2EPKci in unary_function_gpu.o
      __ZN4dmlc15LogMessageFatalD2Ev in unary_function_gpu.o
      __ZN4dmlc15LogMessageFatalC2EPKci in activation_gpu.o
      __ZN4dmlc15LogMessageFatalD2Ev in activation_gpu.o
      __ZN4dmlc15LogMessageFatalC2EPKci in batch_norm_gpu.o
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)


#-------------------------------------------------------------------------------
#  Template configuration for compiling mxnet
#
#  If you want to change the configuration, please use the following
#  steps. Assume you are on the root directory of mxnet. First copy the this
#  file so that any local changes will be ignored by git
#
#  $ cp make/config.mk .
#
#  Next modify the according entries, and then compile by
#
#  $ make
#
#  or build in parallel with 8 threads
#
#  $ make -j8
#-------------------------------------------------------------------------------

#---------------------
# choice of compiler
#--------------------

export CC = clang-omp
export CXX = clang-omp++
export NVCC = nvcc

# whether compile with debug
DEBUG = 0


# the additional link flags you want to add
ADD_LDFLAGS = '-L/usr/local/opt/openblas/lib' '-L/usr/local/cuda/lib'  '-L/usr/local/cudnn/lib'

# the additional compile flags you want to add
ADD_CFLAGS = '-I/usr/local/opt/openblas/include' '-I/usr/local/cuda/include'   '-I/usr/local/cudnn/include'

# per https://github.com/dmlc/mxnet/issues/728#issuecomment-160867057
ADD_LDFLAGS += -Xlinker -F/Library/Frameworks -Xlinker -framework -Xlinker CUDA

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA library to link and compile flag
# if you have already add them to environment variable, leave it as NONE
# USE_CUDA_PATH = /usr/local/cuda
USE_CUDA_PATH = /usr/local/cuda

# whether use CUDNN R3 library
USE_CUDNN = 0

# whether use cuda runtime compiling for writing kernels in native language (i.e. Python)
USE_NVRTC = 0




# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 1

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
USE_BLAS = openblas

# add path to intel library, you may need it for MKL, if you did not add the path
# to environment variable
USE_INTEL_PATH = NONE

#----------------------------
# distributed computing
#----------------------------

# whether or not to enable multi-machine supporting
USE_DIST_KVSTORE = 0

# whether or not allow to read and write HDFS directly. If yes, then hadoop is
# required
USE_HDFS = 0

# path to libjvm.so. required if USE_HDFS=1
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

# whether or not allow to read and write AWS S3 directly. If yes, then
# libcurl4-openssl-dev is required, it can be installed on Ubuntu by
# sudo apt-get install -y libcurl4-openssl-dev
USE_S3 = 0

#----------------------------
# additional operators
#----------------------------

# path to folders containing projects specific operators that you don't want to put in src/operators
EXTRA_OPERATORS =


#----------------------------
# plugins
#----------------------------

# whether to use torch integration. This requires installing torch.
# TORCH_PATH = $(HOME)/torch
# MXNET_PLUGINS += plugin/torch/torch.mk

**Comment by morgado-jb** [comment]
I'm also having all these problems trying to compile the latest version of mxnet.

I don't see a valid reason to close this issue since the bug clearly still exists.

**Comment by piiswrong** [comment]
use make/osx.mk instead of make/config.mk if you are using make. Follow the mac installation instructions, not the linux one

**Comment by piiswrong** [comment]
Make sure your mac actually has a nvidia gpu. Most macs doesn't

**Comment by shadowleaves** [comment]
had similar issue on El Capitan and CUDA 8.0. adding the following string to ADD_LDFLAGS would fix it: **-F/Library/Frameworks -Xlinker -framework -Xlinker CUDA**
please see also the following issue describing fix for similar problem.
https://github.com/arrayfire/arrayfire/issues/1496

**Comment by Walid-Ahmed** [comment]
@shadowleaves 
I added  the line but still have the same issue
my graphics card is Intel Iris Pro 1536 MB so I am not sure it actually supports CUDA or not

**Comment by phunterlau** [comment]
@Walid-Ahmed Intel Iris Pro comes from Intel where CUDA comes from nVidia, a.k.a Intel Iris Pro doesn't support CUDA
