### ISSUE TITLE
how to output svg for graph.viz() function

### ISSUE THREAD

**Issue by caprice-j** [dmlc/mxnet#775]
I'm now executing R from iPython Notebook, and graph.viz() doesn't output its given network.
My ipython notebook can handle plot() and ggplot() output correctly.
Is there a way to render the output as svg or other formats?

Here's the code:

library(mxnet)
data <- mx.symbol.Variable("data")
 fc1 <- mx.symbol.FullyConnected(data, num_hidden=1024)
 lro <- mx.symbol.LinearRegressionOutput(fc1)
graph.viz(lro$as.json())

" graph.viz(lro$as.json(), output='svg') " doesn't work, even render_graph have the augment.
" print( graph.viz(lro$as.json()) )" also doesn't work.

**Comment by thirdwing** [comment]
This should be a problem from  DiagrammeR.

@pommedeterresautee Can you help?

**Comment by pommedeterresautee** [comment]
I don t know how iPython works but the export of SVG from DiagrammeR requires a special version using V8 (https://github.com/rich-iannone/DiagrammeR/pull/79)

However, after email from R core team member, the support of V8 has been removed because it is hard to install/maintain/test on Cran server (we received an email too for XGBoost project).

Some background: https://github.com/rich-iannone/DiagrammeR/issues/137

RMarkdown would not work for you?

Kind regards,
Michaël

**Comment by pommedeterresautee** [comment]
After better search:
https://github.com/rich-iannone/DiagrammeRsvg !!!

**Comment by caprice-j** [comment]
@pommedeterresautee  Fantastic! 
I installed DiagrammeRsvg, and DiagrammeRsvg::export_svg( mxnet::graph.viz( lro$as.json() ) outputted svg correctly on iPython notebook. I appreciate your kind search.
