### ISSUE TITLE
how can i use the grayscale images as training data?

### ISSUE THREAD

**Issue by sofiawu** [dmlc/mxnet#805]
I have a grayscale image dataset and want to use it as the training data. I use the im2rec to convert the images into the rec data for training, It seems that I can not use the data_shape = (1, 64，64) .
when I run the code, it report the error :shape mismatch (1, 64, 64) vs (3, 64, 64).
so what can i do if i want to use the data shape (1,64,64) instead of (3,64,64)??

**Comment by starimpact** [comment]
use shape (1, 1, 64, 64).

**Comment by piiswrong** [comment]
This is because in src/io/iter_image_record.cc:248 we are always decoding image to 3 channels with cv::imdecode(buf, 1). For grey images this just duplicate the grey channel 3 times. It shouldn't hurt if you just set your data shape to (3,64,64). 

However, if you do wan't to fix it, you need to replace `res = cv::imdecode(buf, 1);` with `res = cv::imdecode(buf, -1);` and fix the code following that.
