### ISSUE TITLE
Does mxnet support Stale Synchronous Parallel (aka. SSP)

### ISSUE THREAD

**Issue by butterluo** [dmlc/mxnet#841]
Does mxnet support Stale Synchronous Parallel (aka. SSP) ? Just like Petuum do.
If it doesn't, is there any plan to support SSP?

**Comment by piiswrong** [comment]
I think ps-lite handle async sgd in a different. @mli 
You can read Mu Li's paper for the exact algorithm

**Comment by tqchen** [comment]
The only difference lies on implementation of kvstore while the interface remains the same, so the question becomes if ps-lite currently supported bounded staleness @mli  should be appropriate to answer this.

**Comment by mli** [comment]
The implementation is quite easy, but we find it is not so useful since in
practice the actual delay observed is quite small, probably because the gpu
performance is uniform. Having an additional max delay constraint may bring
confusion to users.

**Comment by qiaohaijun** [comment]
I test SSP a lot, and I find caffe on petuum is not work well as expect.  so I suggest that use async.
if you have a good result, please let me know, I will try it again, using your configure.

**Comment by qiaohaijun** [comment]
The way of update parameter in SSP model is different with ASGD model.

**Comment by butterluo** [comment]
Does mxnet use ps-lite as its kvstore for parameter ? @mli  @tqchen

**Comment by tqchen** [comment]
@butterluo Yes, ps-lite is used as distributed backend, but the interface is quite flexible to change to others when needed. The new ps-lite is quite helpful, and allows you to define custom updates through native language such as python

**Comment by mli** [comment]
@qiaohaijun i follow the notations from the paper [the slow learners are faster](http://alex.smola.org/papers/2009/LanSmoZin09.pdf), which is also compatible with the notations of  bertsekas at mit (i'm a big fan of him). while i guess the petuum guys use the notations from database, one of the original [paper](http://www.cs.cmu.edu/~jcipar/papers/lazybase-eurosys2012.pdf)   

i changed opinions to several guys at nips, i think ssp (or bounded delay) is not necessary at this moment for two reasons:

1. neither significant improvement on speed nor on convergence, due to the gpu dense operation performance is quite uniform.
2. what really matters is a special kind of straggler, namely one worker is blocked for several minutes, and then comes alive again. we probably want to reject its results based on very ancient weights

**Comment by tqchen** [comment]
closing for now, I would say contribution to ps-lite is encouraged if anyone is interested in SSP
