### ISSUE TITLE
How can I get the error feedback backpropagated to a feature map?

### ISSUE THREAD

**Issue by erogol** [dmlc/mxnet#923]
I am able to see the gradient values of network weights but is there any other way to obtain the error feedback projected to feature maps?  For instance if the feature map has size NxCxHxW I like to see the same size gradient feedback propagated to that layer.

**Comment by piiswrong** [comment]
bind it's gradient with args_grad

**Comment by erogol** [comment]
if I am correct  args_grad provides only weight gradients not the ones on the feature maps. I already did this by following adversary example.

**Comment by tqchen** [comment]
To get grad of intermediate nodes was not possible in the currently interface because such request is not yet passed in. mainly because some of them are optimized out. There is one hack that we can do to get the gradient, which is by adding another variable to the requested feature map.

```python
fmap = mx.Convolution(data, num_hidden=10, ..)
dummy = mx.Variable('fmap1')
fmap = fmap + fmap1
```

Then we can pass 0 into dummy in forward and get gradient wrt that feature map in backward

**Comment by piiswrong** [comment]
@tqchen I think you can group the intermediate node with output and then bind

**Comment by erogol** [comment]
@piiswrong could you give a small example for visualizing

**Comment by pluskid** [comment]
Tagging with `HowTo` and closing for now.
