### ISSUE TITLE
Loading a model

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#946]
I was able to train a model for 25 epochs and save the parameters after each one. I wanted to then test it.  I attempted to load the model using

```
for i in range(1, 26):
	model = mx.model.FeedForward.load( 'rambutan', i )
```

I get the following error: 

```
[jmschr@n025 scripts]$ python eval.py
[10:01:31] ./dmlc-core/include/dmlc/logging.h:208: [10:01:31] src/operator/./pooling-inl.h:80: Check failed: (param_.stride[0]) == (param_.stride[1]) Only same stride is supported now
[10:01:31] ./dmlc-core/include/dmlc/logging.h:208: [10:01:31] src/engine/./threaded_engine.h:295: [10:01:31] src/operator/./pooling-inl.h:80: Check failed: (param_.stride[0]) == (param_.stride[1]) Only same stride is supported now
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [10:01:31] src/engine/./threaded_engine.h:295: [10:01:31] src/operator/./pooling-inl.h:80: Check failed: (param_.stride[0]) == (param_.stride[1]) Only same stride is supported now
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted (core dumped)
```

I previous noted that it seemed I was able to set pooling kernels to be bigger than the size of the data. Is this that error? If so, it seems odd that it can train properly, but doesn't want to be loaded later on.

**Comment by piiswrong** [comment]
Could you print param_.stride, or attach your model so we can have a look?

**Comment by jmschrei** [comment]
Here is the first iteration checkpoint.

[rambutan-0001.params.zip](https://github.com/dmlc/mxnet/files/63659/rambutan-0001.params.zip)

**Comment by piiswrong** [comment]
@jmschrei I also need the json file

**Comment by axlesor** [comment]
I encountered similar issues loading a model. If I use example/kaggle-ndsb1, it is working fine, I can load models saved in previous iterations. But for other example/kaggle-ndsb2:
tmp = mx.model.FeedForward.load(model_sty, load_epoch, ctx = mx.cpu())
File "/mxnet/mx_env/lib/python3.4/site-packages/mxnet-0.5.0-py3.4.egg/mxnet/symbol.py", line 769, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/mxnet/mx_env/lib/python3.4/site-packages/mxnet-0.5.0-py3.4.egg/mxnet/base.py", line 76, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Parameter scalar is not presented

Something in lenet model in that exmaple it can not able read back since I checked it is opening the file, parsing is failing.

**Comment by piiswrong** [comment]
You model was created using ctx=mx.gpu() and you are trying to load it with ctx=mx.cpu().
Only gpu version supports different stride. Load with gpu and you should be fine.

**Comment by axlesor** [comment]
Unfortunately using gpu still fails the same way:
tmp = mx.model.FeedForward.load(model_sty, load_epoch, ctx = mx.gpu())
  File "/mxnet/mx_env/lib/python3.4/site-packages/mxnet-0.5.0-py3.4.egg/mxnet/model.py", line 344, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/mxnet/mx_env/lib/python3.4/site-packages/mxnet-0.5.0-py3.4.egg/mxnet/symbol.py", line 769, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/mxnet/mx_env/lib/python3.4/site-packages/mxnet-0.5.0-py3.4.egg/mxnet/base.py", line 76, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))

I think issue is that model in kaggle-ndsb2 has some image processing which it cannot able to load. Since my GPU is 860M, I like to run it in small chunks to prevent overheating so I prefer saving/loading models. possinbly the original ticket has also has some complex model that is failing. Since main code is C it is difficult to to debug from python side exactly what part it is failing.
